version: "3.7"
services:
  node1:
    build: .
    ports:
      - "3001:3001"
      - "2501:3000"
      - "2001:2999"
    volumes:
      - ./node1:/app/
    command: "/bin/sh -c 'cd /app && ./river_core'"
    networks:
      river_core:
        ipv4_address: 172.26.0.2
  node2:
    build: .
    ports:
      - "3002:3001"
      - "2502:3000"
      - "2002:2999"
    volumes:
      - ./node2:/app/
    command: "/bin/sh -c 'cd /app && ./river_core'"
    networks:
      river_core:
        ipv4_address: 172.26.0.3
  node3:
    build: .
    ports:
      - "3003:3001"
      - "2503:3000"
      - "2003:2999"
    volumes:
      - ./node3:/app/
    command: "/bin/sh -c 'cd /app && ./river_core'"
    networks:
      river_core:
        ipv4_address: 172.26.0.4

networks:
  river_core:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1
